FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build --prod --skip-tests

FROM nginx:alpine

RUN rm -r /usr/share/nginx/html/index.html

COPY --from=build /app/dist/project/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
