name: Java CI with Maven

on:
  push:
    paths:
      - 'Projet-E2425G3_1-back/**' 
    branches: [ "main" ]
  pull_request:
    paths:
      - 'Projet-E2425G3_1-back/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Step 3: Build the project in the specific folder
    - name: Build with Maven
      working-directory: Projet-E2425G3_1-back
      run: mvn -B package -DskipTests

    # Step 4: SonarCloud analysis
    - name: SonarCloud Scan
      working-directory: Projet-E2425G3_1-back
      run: |
        mvn verify -DskipTests \
          -Dsonar.projectKey=applicationgestionprojetsorg_applicationgestionprojets \
          -Dsonar.organization=applicationgestionprojetsorg \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
